version: 'v1.0'
services:
  registry:
    container_name: registry
    restart: always
    build:
      context: .
      dockerfile: registry/dockerfile
    volumes:
      - .:/code
    ports:
      - "9001:9001"