apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: sba-mysql
  namespace: sba
  labels:
    name: sba-mysql
    version: v1
spec:
  replicas: 1
  selector:
    name: sba-mysql
    version: v1
  template:
    metadata:
      labels:
        name: sba-mysql
        version: v1
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/wujiabo/mysql:latest
          name: sba-mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 123456
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          hostPath:
            path: /data/mysql