FROM java:8-jre
MAINTAINER xxx xx@xxxxx.com
VOLUME /vol/development
RUN mkdir -p /vol/development
WORKDIR /vol/development
COPY gateway/target/*.jar /vol/development/app.jar
CMD ["java", "-Xmx200m", "-Djava.security.egd=file:/dev/./urandom","-jar","/vol/development/app.jar"]