spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: sba-gateway
server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    securePortEnabled: true
    instance-id: ${spring.application.name}:${server.port}

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS

# 网关配置

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # 停用超时设置
        isolation:
          thread:
            timeoutInMilliseconds: 80000

swagger.enabled: true


apiurl:
  gatewayurl: http://localhost:9002

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    sba-payment:
      path: /payment/**
      serviceId: sba-payment
      stripPrefix: true
      sensitiveHeaders:
    sba-search:
      path: /search/**
      serviceId: sba-search
      stripPrefix: true
      sensitiveHeaders:
    sba-security:
      path: /security/**
      serviceId: sba-security
      stripPrefix: true
      sensitiveHeaders: Cookie,Set-Cookie # Exclude authorization from sensitive headers 
    sba-technology:
      path: /technology/**
      serviceId: sba-technology
      stripPrefix: true
      sensitiveHeaders:
    sba-training:
      path: /training/**
      serviceId: sba-training
      stripPrefix: true
      sensitiveHeaders:
    sba-user:
      path: /user/**
      serviceId: sba-user
      stripPrefix: true
      sensitiveHeaders:

---
spring:
  profiles: k8s
  application:
    name: sba-gateway
server:
  port: 9002


eureka:
  client:
    service-url:
      defaultZone: http://sba-registry:9001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS

  # 网关配置


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # 停用超时设置
        isolation:
          thread:
            timeoutInMilliseconds: 80000

swagger.enabled: true

apiurl:
  gatewayurl: http://sba-gateway:9002

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    sba-payment:
      path: /payment/**
      serviceId: sba-payment
      stripPrefix: true
      sensitiveHeaders:
    sba-search:
      path: /search/**
      serviceId: sba-search
      stripPrefix: true
      sensitiveHeaders:
    sba-security:
      path: /security/**
      serviceId: sba-security
      stripPrefix: true
      sensitiveHeaders: Cookie,Set-Cookie # Exclude authorization from sensitive headers 
    sba-technology:
      path: /technology/**
      serviceId: sba-technology
      stripPrefix: true
      sensitiveHeaders:
    sba-training:
      path: /training/**
      serviceId: sba-training
      stripPrefix: true
      sensitiveHeaders:
    sba-user:
      path: /user/**
      serviceId: sba-user
      stripPrefix: true
      sensitiveHeaders: