eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

spring:
  application:
    name: sba-payment
  datasource:
    url: jdbc:mysql://localhost:3306/sba?useSSL=false
    username: root
    password: 123456
server:
  port: 8001