spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: sba-technology
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sba?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
server:
  servlet:
    context-path: /technology
  port: 8004


logging:
  level:
    com:
      sba:
        technology:
          mapper: Debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
      #        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS

swagger.enabled: true

---
spring:
  profiles: k8s
  application:
    name: sba-technology
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sba?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
server:
  servlet:
    context-path: /technology
  port: 8004

eureka:
  client:
    service-url:
      defaultZone: http://sba-registry:9001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
      #        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS

swagger.enabled: true
